import type { NextPage } from "next";
import styled from "styled-components";
import Head from "next/head";
import DisplayWalletBalance from "../components/organisms/DisplayWalletBalance";
import Navbar from "../components/organisms/Navbar";

// TODO widget component
//  All positions value
// topp 3 mest investerade assets, eller topp 3 som gått med mest vinst?
// <button>Trigger todays run if not yet done</button>
// <div>latest done orders</div>

const PageContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
`;

const ContentContainer = styled.div`
  display: flex;
  gap: 15px;
  flex-direction: column;
`;

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Jaws</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageContainer>
          <ContentContainer>
            <DisplayWalletBalance />
            ...add widgets
          </ContentContainer>
        </PageContainer>
      </main>
    </div>
  );
};

export default Home;
