import type { NextPage } from "next";
import Link from "next/link";
import Head from "next/head";
import RectangularButton from "../components/atoms/buttons/RectangularButton";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Jaws</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <p>
          <Link href="/daily-run">
            <RectangularButton label={"Todays run"} variant="contained" />
          </Link>
        </p>
        <p>
          <Link href="/previous-runs">
            <RectangularButton label={"Previous runs"} variant="contained" />
          </Link>
        </p>
      </main>
    </div>
  );
};

export default Home;
