import type { NextPage } from "next";
import styled from "styled-components";
import Head from "next/head";
import { getToday } from "../lib/helpers";
import NavButton from "../components/atoms/buttons/NavButton";
import TextDisplay from "../components/molecules/TextDisplay";
import DisplayWalletBalance from "../components/organisms/DisplayWalletBalance";

const PageContainer = styled.div`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  height: 100vh;
`;

const ContentContainer = styled.div`
  display: flex;
  gap: 15px;
  flex-direction: column;
`;

const Home: NextPage = () => {
  const today = getToday();

  return (
    <div>
      <Head>
        <title>Jaws</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <PageContainer>
          <ContentContainer>
            <NavButton href={`/daily-runs/${today}`}>Todays run</NavButton>
            <NavButton href="/daily-runs">All runs</NavButton>
            <NavButton href="/orders">All Orders</NavButton>
            <DisplayWalletBalance />
          </ContentContainer>
        </PageContainer>
      </main>
    </div>
  );
};

export default Home;
